Adds support for rails 8.0
alecdotninja/active_record_distinct_on pull request #32
Opened 2024-12-12 10:45 UTC by manuelvanrijn

Rails 8.0 has been released, and this PR will bump the dependency and add an appraise for it.

I've also removed the upper version constraint as mentiond by @ezekg in #31 

[edgeguides.rubyonrails.org/8_0_release_notes.html](https://edgeguides.rubyonrails.org/8_0_release_notes.html)

Closes: #31

2024-12-12 11:12 UTC, manuelvanrijn commented on gemfiles/8.0.gemfile
> +gem "activerecord", "~> 8.0"
😆 weird it sees this as a move file :)

2024-12-12 22:23 UTC, ezekg requested changes

2024-12-12 22:23 UTC, ezekg commented on .github/workflows/test.yml
> +        exclude:
Assuming this is excluded because Rails changed the minimum Ruby version?

Can we make that clearer via a comment?

2024-12-12 22:24 UTC, ezekg commented
Thanks a lot for the PR! One minor change i.r.t. CI.

2024-12-14 22:29 UTC, merged

2024-12-14 22:33 UTC, ezekg commented
No worries, I got it. 👍 Published in v1.8.0!

2024-12-17 14:33 UTC, manuelvanrijn commented
Thanks @ezekg and yes, it was because Rails 8 requires Ruby 3.2+ :)